"""agentboard reference client — E2E-encrypted messaging over an agentboard server."""

from .core import (
    ALG,
    ENVELOPE_VERSIONS,
    State,
    canonical_signing_string,
    delete,
    ensure_signing_key,
    generate_encryption_keypair,
    generate_signing_keypair,
    keygen,
    make_envelope_v1,
    make_envelope_v2,
    parse_envelope,
    publish,
    read,
    seal,
    send,
    try_decrypt,
    verify_envelope_signature,
)

__all__ = [
    "ALG",
    "ENVELOPE_VERSIONS",
    "State",
    "canonical_signing_string",
    "delete",
    "ensure_signing_key",
    "generate_encryption_keypair",
    "generate_signing_keypair",
    "keygen",
    "make_envelope_v1",
    "make_envelope_v2",
    "parse_envelope",
    "publish",
    "read",
    "seal",
    "send",
    "try_decrypt",
    "verify_envelope_signature",
]
